version: '3.4'


services:
  back:
    image: back
    build: ./services/back
    hostname: back
    container_name: back
    ports:
      - 8080:8080
    working_dir: /app
    command: |
      mvn spring-boot:run 

  front:
    image: front
    hostname: front
    container_name: front
    working_dir: /app
    build: 
      context: ./services/client
      args:
        PORT: 4444
        IP: $IP
        SESSION: TEST_ID       # local conf 
        # SESSION: $SESSION_ID # prod  conf
        BACK_PORT: 8080        # 8080 local testing | 80 pwd
        BACK_PWD: 8080
    ports:
      - 4444:4444
    env_file: 
      - .env
    environment:
      HOST: 0.0.0.0
      PORT: 4444
      IP: $IP


networks:
  default:
    external:
      name: app

