version: '3.4'


services:
  back:
    image: app
    hostname: back
    container_name: back
    build: ./
    ports:
      - 8080:8080
    working_dir: /app
    command: |
      ./mvnw spring-boot:run 

  front:
    image: app
    hostname: front
    container_name: front
    working_dir: /app
    ports:
      - 4444:4444
    command: |
      sh -c "
      cd client
      npm install
      PORT=4444 npm start "


networks:
  default:
    external:
      name: app

