version: '3.4'


services:
  back:
    image: back
    build: ./app/back
    hostname: back
    container_name: back
    ports:
      - 8080:8080
    working_dir: /app
    command: |
      mvn spring-boot:run 

  front:
    image: front
    build: ./app/client
    hostname: front
    container_name: front
    working_dir: /app/client
    ports:
      - 4444:4444
    environment:
      HOST: 0.0.0.0
      PORT: 4444
    command: |
      npm start

networks:
  default:
    external:
      name: app

